# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 665f8ab567fdaa734e6a02bb7bee75cc8d9dc1930c4a2a57e037d05607f8ed92e34102d118ad75dc7bb0f5d987731707bbe1c1a72ea58a3e638b4d1ec020ef8a

test:
  secret_key_base: 2c83719a6c815532d972235dd307fdca095265e0a9d4d84f2b57c766b5a652d3cc9641299750f39c5503107f196f849fd035030d4522212dcd7120b746f31fbe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
